# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import pyas2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdn',
            name='headers',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pyas2.models.get_mdn_store),
        ),
        migrations.AlterField(
            model_name='mdn',
            name='payload',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pyas2.models.get_mdn_store),
        ),
        migrations.AlterField(
            model_name='message',
            name='headers',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pyas2.models.get_message_store),
        ),
        migrations.AlterField(
            model_name='message',
            name='payload',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pyas2.models.get_message_store),
        ),
    ]
