# Generated by Django 2.2.1 on 2019-05-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccertificate',
            name='certificate_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publiccertificate',
            name='certificate_valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
