# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0002_auto_20180414_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='mdn_sign',
            field=models.CharField(blank=True, choices=[('sha1', 'SHA-1'), ('sha256', 'SHA-256')], max_length=20, null=True, verbose_name='Request Signed MDN'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='signature',
            field=models.CharField(blank=True, choices=[('sha1', 'SHA-1'), ('sha256', 'SHA-256')], max_length=20, null=True, verbose_name='Sign Message'),
        ),
    ]
