# Generated by Django 4.2.6 on 2023-10-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0003_auto_20221208_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email_address',
            field=models.EmailField(blank=True, help_text='This email will be used for the Disposition-Notification-To header. If left blank, header defaults to: no-reply@pyas2.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cmd_receive',
            field=models.TextField(blank=True, help_text='Command executed after successful message receipt, replacements are $filename, $fullfilename, $sender, $receiver, $messageid and any message header such as $Subject', null=True, verbose_name='Command on Message Receipt'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cmd_send',
            field=models.TextField(blank=True, help_text='Command executed after successful message send, replacements are $filename, $sender, $receiver, $messageid and any message header such as $Subject', null=True, verbose_name='Command on Message Send'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='content_type',
            field=models.CharField(choices=[('application/EDI-X12', 'application/EDI-X12'), ('application/EDIFACT', 'application/EDIFACT'), ('application/edi-consent', 'application/edi-consent'), ('application/XML', 'application/XML'), ('application/octet-stream', 'binary')], default='application/edi-consent', max_length=100),
        ),
    ]
