# Generated by Django 3.1.7 on 2022-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyas2", "0003_auto_20221208_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="canonicalize_as_binary",
            field=models.BooleanField(
                default=False, verbose_name="Force binary canonicalization"
            ),
        ),
    ]
