# Generated by Django 2.2.1 on 2019-06-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0004_auto_20190602_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='serial_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='publiccertificate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
